# Gotta populate the groups dictionary
- hosts: tag_Name_master
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: Ping the master/s
      ping:
- hosts: tag_Name_slaves
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: Ping item
      ping:
    - name: update hosts file
      template: src=./test.j2 dest=/test.txt
